import type {ProviderOffer,ServiceConfiguration} from './service-model';

export type Service={id:string;category:string;title:string;description:string;price:number;days:number;provider?:string;image:string;tags:string[];deliverables:string[];configuration?:ServiceConfiguration;offers?:ProviderOffer[]};
export const categories=[['all','الكل'],['design','التصميم والهوية'],['code','البرمجة والتقنية'],['marketing','التسويق الرقمي'],['writing','الكتابة والترجمة'],['video','الفيديو والموشن'],['audio','الصوتيات'],['business','الأعمال'],['data','البيانات والذكاء الاصطناعي']];
export const services:Service[]=[
{id:'shop',category:'code',title:'متجرك الإلكتروني، جاهز للانطلاق',description:'تأسيس متجر متكامل على المنصة المناسبة، بهوية تشبه مشروعك.',price:950,days:5,image:'shop-v3',tags:['shop','growth'],deliverables:['إعداد المتجر والتصنيفات','إضافة 15 منتجًا بمحتواها','تهيئة الدفع والشحن','شرح مبسط لإدارة المتجر'],offers:[
 {id:'abdullah',name:'عبدالله السالم',role:'متخصص في تأسيس متاجر سلة وزد',priceDelta:0,days:5,rating:'4.9',completed:38,badge:'الأكثر خبرة'},
 {id:'sarah',name:'سارة العتيبي',role:'تجربة متجر ومحتوى المنتجات',priceDelta:180,days:6,rating:'5.0',completed:24,badge:'أنسب للمحتوى'},
 {id:'ahmed',name:'أحمد المطيري',role:'إطلاق سريع وربط الأدوات',priceDelta:320,days:3,rating:'4.8',completed:46,badge:'الأسرع'}
],configuration:{intro:'جاوب عن اللي تعرفه فقط؛ الخيارات ترتّب النطاق والسعر بدون ما تحوّلك لصفحة ثانية.',fields:[
 {id:'store-state',type:'choice',label:'وين وصلت في متجرك؟',choices:[{id:'new',label:'أبدأ من الصفر',description:'ما عندي متجر حتى الآن',recommended:true},{id:'existing',label:'عندي متجر',description:'وأحتاج إكمال الإعداد أو تحسينه'}]},
 {id:'platform',type:'choice',label:'أي منصة تناسبك؟',hint:'إذا ما تعرف، نخلي المختص يقترحها بعد فهم نشاطك.',choices:[{id:'salla',label:'سلة',description:'مناسبة للسوق السعودي'},{id:'zid',label:'زد',description:'متجر وإدارة عمليات'},{id:'shopify',label:'Shopify',description:'مرونة وتوسّع عالمي'},{id:'unsure',label:'ما أعرف',description:'رشّحوا لي الأنسب',recommended:true},{id:'other',label:'منصة أخرى'}]},
 {id:'other-platform',type:'text',label:'اسم المنصة',placeholder:'اكتب اسم المنصة',visibleWhen:[{field:'platform',equals:'other'}],attachedTo:{field:'platform',choice:'other'}},
 {id:'subscription',type:'choice',label:'هل اشتراك المنصة جاهز؟',visibleWhen:[{field:'platform',anyOf:['salla','zid','shopify']}],choices:[{id:'active',label:'نعم، جاهز'},{id:'need',label:'أحتاج اشتراكًا'},{id:'unsure',label:'ماني متأكد',description:'نتأكد معك قبل أي تكلفة'}]},
 {id:'salla-plan',type:'choice',label:'أي باقة من سلة؟',visibleWhen:[{field:'platform',equals:'salla'},{field:'subscription',equals:'need'}],choices:[{id:'plus',label:'بلس',description:'99 ر.س شهريًا',recommended:true},{id:'pro',label:'برو',description:'299 ر.س شهريًا'},{id:'unsure',label:'أحتاج ترشيحًا'}]},
 {id:'billing',type:'choice',label:'طريقة الاشتراك',visibleWhen:[{field:'platform',equals:'salla'},{field:'subscription',equals:'need'},{field:'salla-plan',anyOf:['plus','pro']}],choices:[{id:'monthly',label:'شهري'},{id:'yearly',label:'سنوي',description:'أوفر على المدى الطويل',recommended:true}]},
 {id:'products',type:'number',label:'كم منتج نجهّز لك؟',hint:'أول 15 منتجًا مشمولة في السعر.',min:1,max:200,step:1,defaultValue:15,unit:'منتج'},
 {id:'identity',type:'choice',label:'هل هويتك جاهزة؟',choices:[{id:'ready',label:'جاهزة',description:'الشعار والألوان والخطوط'},{id:'light',label:'أحتاج تهيئة بسيطة',description:'لوحة ألوان وخطوط للمتجر'},{id:'unsure',label:'ماني متأكد',description:'يراجعها المختص معك',recommended:true}]},
 {id:'launch-date',type:'date',label:'متى تبي يكون المتجر جاهزًا؟',hint:'اختياري؛ نستخدمه للتأكد من توفر المختص.',optional:true,minDateOffset:1,maxDateOffset:180}
],priceRules:[
 {id:'products-50',label:'إعداد منتجات إضافية',kind:'execution',amount:350,when:[{field:'products',gte:16},{field:'products',lte:50}]},
 {id:'identity-light',label:'تهيئة هوية المتجر',kind:'execution',amount:400,when:[{field:'identity',equals:'light'}]},
 {id:'salla-plus-monthly',label:'اشتراك سلة بلس',kind:'external',amount:99,cadence:'شهريًا',when:[{field:'salla-plan',equals:'plus'},{field:'billing',equals:'monthly'}]},
 {id:'salla-plus-yearly',label:'اشتراك سلة بلس',kind:'external',amount:990,cadence:'سنويًا',when:[{field:'salla-plan',equals:'plus'},{field:'billing',equals:'yearly'}]},
 {id:'salla-pro-monthly',label:'اشتراك سلة برو',kind:'external',amount:299,cadence:'شهريًا',when:[{field:'salla-plan',equals:'pro'},{field:'billing',equals:'monthly'}]},
 {id:'salla-pro-yearly',label:'اشتراك سلة برو',kind:'external',amount:2990,cadence:'سنويًا',when:[{field:'salla-plan',equals:'pro'},{field:'billing',equals:'yearly'}]}
],quoteRules:[{when:[{field:'products',gte:51}]}],requirements:['شعار وهوية إن كانت متوفرة','بيانات التواصل والشحن','صور المنتجات ومعلوماتها'],exclusions:['رسوم اشتراك المنصة','تكلفة التطبيقات المدفوعة','التصوير أو كتابة محتوى أكثر من النطاق'],works:[
 {id:'shop-work-1',title:'متجر عناية بواجهة هادئة',image:'shop-v3',providerId:'sarah',provider:'سارة العتيبي',need:'إطلاق متجر واضح وسهل لمنتجات عناية محلية.',result:'واجهة مرتبة وتجربة شراء مختصرة مع تجهيز المحتوى لأول 24 منتجًا.',scope:['تنظيم التصنيفات','تهيئة صفحات المنتجات','ضبط الهوية على الواجهة'],gallery:['shop-v3','products-v2','content-v2']},
 {id:'shop-work-2',title:'تجهيز متجر وإطلاقه خلال أسبوع',image:'css-v3',providerId:'abdullah',provider:'عبدالله السالم',need:'نقل مشروع قائم إلى متجر يستقبل الطلبات والدفع.',result:'إطلاق متجر متجاوب وربط الدفع والشحن مع تسليم شرح للإدارة.',scope:['إعداد سلة','ربط الدفع والشحن','اختبار رحلة الطلب'],gallery:['css-v3','landing-v2','shop-v2']}
]}},
{id:'brand',category:'design',title:'هوية بصرية تترك أثرًا',description:'من الشعار إلى أدق التفاصيل. هوية تُعرف بها.',price:1500,days:7,provider:'نورة الحربي',image:'brand-v3',tags:['brand','charity'],deliverables:['اتجاهان مبدئيان للشعار','لوحة ألوان وخطوط','بطاقة عمل وورق مراسلات','دليل استخدام الهوية وملفات مفتوحة'],configuration:{intro:'نحدّد نطاق الهوية أولًا، ثم تشوف العرض بوضوح.',fields:[{id:'brand-state',type:'choice',label:'وش تحتاج لهويتك؟',choices:[{id:'logo',label:'شعار فقط'},{id:'starter',label:'هوية بداية',description:'شعار وألوان وخطوط',recommended:true},{id:'full',label:'هوية متكاملة',description:'مع تطبيقات ودليل استخدام'}]},{id:'brand-use',type:'choice',label:'وين راح تستخدمها أكثر؟',choices:[{id:'digital',label:'القنوات الرقمية'},{id:'print',label:'المطبوعات'},{id:'both',label:'الاثنين',recommended:true}]}],priceRules:[{id:'brand-logo',label:'نطاق الشعار فقط',kind:'execution',amount:-400,when:[{field:'brand-state',equals:'logo'}]},{id:'brand-full',label:'تطبيقات الهوية ودليلها',kind:'execution',amount:900,when:[{field:'brand-state',equals:'full'}]}],requirements:['اسم المشروع ونشاطه','أمثلة بصرية قريبة من ذوقك'],exclusions:['تسجيل العلامة التجارية','الطباعة والإنتاج'],works:[{id:'brand-work-1',title:'هوية مشروع مجتمعي',image:'brand-v3',providerId:'noura',provider:'نورة الحربي',need:'هوية دافئة وحديثة تصلح رقميًا ومطبوعًا.',result:'نظام بصري واضح يسهّل إنتاج المواد اليومية بدون تشتيت.',scope:['شعار مرن','نظام ألوان وخطوط','قوالب استخدام']}]},offers:[{id:'noura',name:'نورة الحربي',role:'مصممة هويات وعلامات ناشئة',priceDelta:0,days:7,rating:'5.0',completed:31,badge:'صاحبة العمل المعروض'}]},
{id:'pixel',category:'marketing',title:'ربط بكسل TikTok بمتجرك',description:'تتبّع الزيارات والإضافات للسلة وإتمام الشراء.',price:180,days:1,image:'pixel-v3',tags:['shop','growth'],deliverables:['تثبيت البكسل','إعداد الأحداث الأساسية','التحقق من استقبال الأحداث','تقرير باختبار الربط'],configuration:{intro:'اختياران سريعين يكفون لتحديد طريقة الربط.',fields:[{id:'pixel-platform',type:'choice',label:'متجرك على أي منصة؟',choices:[{id:'salla',label:'سلة'},{id:'zid',label:'زد'},{id:'shopify',label:'Shopify'},{id:'other',label:'منصة أخرى'}]},{id:'pixel-access',type:'choice',label:'هل حساب TikTok Ads جاهز؟',choices:[{id:'ready',label:'جاهز'},{id:'setup',label:'أحتاج إعداد الحساب',description:'نضيفه إلى نطاق التنفيذ'},{id:'unsure',label:'ماني متأكد',recommended:true}]}],priceRules:[{id:'ads-setup',label:'تهيئة حساب الإعلانات',kind:'execution',amount:120,when:[{field:'pixel-access',equals:'setup'}]}],requirements:['صلاحية المتجر','صلاحية حساب TikTok Ads'],exclusions:['الإنفاق الإعلاني','إدارة الحملات بعد الربط']},offers:[{id:'abdullah',name:'عبدالله السالم',role:'قياس وربط متاجر إلكترونية',priceDelta:0,days:1,rating:'4.9',completed:62,badge:'الأكثر تنفيذًا'},{id:'ahmed',name:'أحمد المطيري',role:'تحليلات وأحداث تتبع',priceDelta:80,days:1,rating:'5.0',completed:29}]},
{id:'css',category:'code',title:'واجهة متجر على ذوق علامتك',description:'تخصيص واجهة متجرك باستخدام CSS وJavaScript.',price:650,days:4,provider:'عبدالله السالم',image:'css-v3',tags:['shop','brand'],deliverables:['تخصيص الصفحة الرئيسية','تكييف الألوان والخطوط','تحسين العرض على الجوال','تسليم ملفات CSS وJavaScript']},
{id:'content',category:'writing',title:'كلمات تشبه مشروعك',description:'محتوى موقعك من أول ترحيب إلى آخر دعوة للتواصل.',price:500,days:4,provider:'سارة العتيبي',image:'content-v2',tags:['brand','charity'],deliverables:['محتوى 5 صفحات','نبرة كتابة خاصة بالعلامة','مراجعة لغوية','جولة تعديلات واحدة']},
{id:'reels',category:'video',title:'مقاطع قصيرة، حضور أكبر',description:'مونتاج ثلاثة مقاطع من لقطاتك للتواصل الاجتماعي.',price:480,days:3,provider:'فيصل الدوسري',image:'reels-v2',tags:['growth','shop'],deliverables:['3 مقاطع عمودية','عناوين وترجمة','تصحيح الألوان','ملفات جاهزة للنشر']},
{id:'charity',category:'code',title:'موقع يُبرز أثر جمعيتك',description:'برامجكم وقصص أثركم وفرص التطوع في مكان واحد.',price:2400,days:10,provider:'أحمد المطيري',image:'charity-v3',tags:['charity'],deliverables:['5 صفحات متجاوبة','عرض البرامج والمبادرات','نموذج لطلبات التطوع','تدريب على إدارة المحتوى']},
{id:'report',category:'design',title:'تقرير سنوي يحكي الأثر',description:'نحوّل إنجازات جمعيتكم إلى تقرير واضح وجميل.',price:850,days:6,provider:'مشاعل العنزي',image:'report-v2',tags:['charity'],deliverables:['تصميم 20 صفحة','تنسيق الأرقام والرسوم','نسخة رقمية للطباعة','جولتان من التعديلات']},
{id:'campaign',category:'marketing',title:'حملتك القادمة تبدأ بخطة',description:'إعداد حملة إعلانية على منصة واحدة. الإنفاق الإعلاني منفصل.',price:750,days:4,image:'campaign-v2',tags:['growth','charity'],deliverables:['تحديد الجمهور','إعداد حملة واحدة','3 نصوص إعلانية','تقرير الإعداد'],configuration:{intro:'نفرّق لك من البداية بين أجر التنفيذ وميزانية الإعلان.',fields:[{id:'campaign-platform',type:'choice',label:'وين تبي تظهر حملتك؟',choices:[{id:'meta',label:'Instagram وFacebook'},{id:'tiktok',label:'TikTok'},{id:'google',label:'Google'},{id:'unsure',label:'رشّحوا لي',recommended:true}]},{id:'campaign-goal',type:'choice',label:'وش أهم نتيجة لك؟',choices:[{id:'sales',label:'مبيعات'},{id:'leads',label:'طلبات وتواصل'},{id:'awareness',label:'انتشار ووعي'},{id:'unsure',label:'نحددها سوا'}]},{id:'campaign-scope',type:'choice',label:'تحتاج إعدادًا أو إدارة؟',choices:[{id:'setup',label:'إعداد وإطلاق فقط',description:'تسليم الحملة جاهزة',recommended:true},{id:'month',label:'إدارة لمدة شهر',description:'متابعة وتحسين أسبوعي'}]},{id:'ad-budget',type:'choice',label:'ميزانية الإعلان المتوقعة',hint:'هذه تذهب لمنصة الإعلان وليست من رسوم مقدم الخدمة.',choices:[{id:'starter',label:'1,000 ر.س',description:'بداية واختبار'},{id:'growth',label:'3,000 ر.س',description:'نطاق أوسع',recommended:true},{id:'scale',label:'5,000 ر.س أو أكثر'}]}],priceRules:[{id:'campaign-month',label:'إدارة وتحسين لمدة شهر',kind:'execution',amount:1200,when:[{field:'campaign-scope',equals:'month'}]},{id:'ads-1000',label:'ميزانية منصة الإعلان',kind:'external',displayAmount:'1,000 ر.س مقترحة',when:[{field:'ad-budget',equals:'starter'}]},{id:'ads-3000',label:'ميزانية منصة الإعلان',kind:'external',displayAmount:'3,000 ر.س مقترحة',when:[{field:'ad-budget',equals:'growth'}]},{id:'ads-5000',label:'ميزانية منصة الإعلان',kind:'external',displayAmount:'5,000+ ر.س',when:[{field:'ad-budget',equals:'scale'}]}],requirements:['حساب إعلاني وصلاحية الوصول','رابط المنتج أو صفحة الهبوط','مواد بصرية إن كانت متوفرة'],exclusions:['ميزانية الإعلان المدفوعة للمنصة','إنتاج تصوير جديد'],works:[{id:'campaign-work-1',title:'حملة تسجيل لمبادرة مجتمعية',image:'campaign-v2',providerId:'reem',provider:'ريم القحطاني',need:'رفع التسجيل في مبادرة خلال مدة محدودة وميزانية واضحة.',result:'هيكلة حملة واحدة بثلاث رسائل واختبار جمهورين مع تقرير ختامي.',scope:['خطة القنوات','إعداد الإعلانات','تحسين أسبوعي']}]},offers:[{id:'reem',name:'ريم القحطاني',role:'حملات أداء للمتاجر والمبادرات',priceDelta:0,days:4,rating:'4.9',completed:35,badge:'صاحبة العمل المعروض'},{id:'faisal',name:'فيصل الدوسري',role:'محتوى إعلاني وفيديو قصير',priceDelta:250,days:5,rating:'4.8',completed:21}]},
{id:'voice',category:'audio',title:'صوت يوصل رسالتك',description:'تعليق صوتي بلهجة سعودية يناسب علامتك.',price:250,days:2,provider:'راكان الشهري',image:'voice-v2',tags:['brand','charity'],deliverables:['تسجيل حتى 150 كلمة','معالجة وتنقية الصوت','نسختا WAV وMP3','تعديل واحد للأداء']},
{id:'presentation',category:'business',title:'عرض يقدّم فكرتك بثقة',description:'ترتيب محتواك وتصميم عرض من عشر شرائح.',price:700,days:5,provider:'هند الغامدي',image:'presentation-v2',tags:['brand','charity'],deliverables:['تصميم 10 شرائح','تنسيق المحتوى','ملف PowerPoint مفتوح','نسخة PDF']},
{id:'dashboard',category:'data',title:'أرقامك، في صورة أوضح',description:'لوحة تفاعلية بخمسة مؤشرات من ملف بيانات واحد.',price:850,days:6,provider:'أمل المالكي',image:'dashboard-v2',tags:['growth','shop'],deliverables:['تنظيم مصدر البيانات','5 مؤشرات أداء','لوحة معلومات تفاعلية','شرح الاستخدام']},
{id:'landing',category:'code',title:'صفحة هبوط لهدفك القادم',description:'صفحة متجاوبة تشرح عرضك وتقود الزائر للخطوة التالية.',price:1200,days:7,image:'landing-v2',tags:['growth','brand'],deliverables:['5 أقسام للمحتوى','نموذج تواصل','تهيئة للجوال','ربط النطاق']},
{id:'products',category:'writing',title:'وصف منتجات يقرب الصورة',description:'نصوص واضحة لعشرة منتجات تبرز التفاصيل والفوائد.',price:300,days:3,provider:'لينا الزهراني',image:'products-v2',tags:['shop'],deliverables:['وصف 10 منتجات','عنوان لكل منتج','مميزات بصياغة واضحة','مراجعة لغوية']},
{id:'motion',category:'video',title:'فكرتك تتحرك وتتكلم',description:'فيديو موشن مدته 30 ثانية من نصك المعتمد.',price:1400,days:8,provider:'محمد العتيبي',image:'motion-v2',tags:['brand','charity'],deliverables:['لوحة مشاهد','30 ثانية موشن','موسيقى مرخصة','نسخة عالية الدقة']},
{id:'automation',category:'data',title:'خل المهام المتكررة علينا',description:'ربط تطبيقين وأتمتة مسار عمل واحد واضح.',price:550,days:3,provider:'يوسف الحارثي',image:'automation-v2',tags:['growth','shop'],deliverables:['ربط تطبيقين','مسار أتمتة واحد','اختبار التشغيل','شرح التعديل والمتابعة']}
];
